# [AI GENERATED] LLM: GitHub Copilot, Mode: Chat, Date: 2025-08-21
{{- if .Values.podDisruptionBudget.enabled }}
{{- range $serviceName, $service := .Values.services }}
{{- if $service.enabled }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "school-microservice.fullname" $ }}-{{ $serviceName }}
  namespace: {{ $.Values.namespace.name }}
  labels:
    {{- include "school-microservice.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $serviceName }}
spec:
  {{- if $.Values.podDisruptionBudget.minAvailable }}
  minAvailable: {{ $.Values.podDisruptionBudget.minAvailable }}
  {{- end }}
  {{- if $.Values.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ $.Values.podDisruptionBudget.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "school-microservice.selectorLabels" $ | nindent 6 }}
      app.kubernetes.io/component: {{ $serviceName }}
{{- end }}
{{- end }}
{{- end }}
