{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "school-management.fullname" . }}-service-monitor
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "school-management.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "school-management.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: /metrics
      interval: {{ .Values.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout }}
  namespaceSelector:
    matchNames:
      - {{ .Values.namespace }}
{{- end }}
